### ISSUE TITLE
default gas usage

### ISSUE THREAD

**Issue by Yelvabaoji** [MOACChain/MOACMask#1]
By send some moac to an address, a default gas usage, which is 1000,  leave in the field. and after i click "next", a popup dialog box remind that gas usage should at least to be 21000. 
here recommend set the default gas usage to 21000 instead of 1000.

**Comment by dacelee** [comment]
https://github.com/dacelee/MOACMask/issues/1

**Comment by mdranger** [comment]
This is fixed in the v0.1.2 release. Thanks for the information.
